# Generated by Django 3.2.9 on 2022-03-30 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geointeligence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indicator',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='topic',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
